services:
  _defaults:
    autoconfigure: true
    public: false

  DirkKlemmt\ContaoMmenuBundle\DataContainer\ModuleCallbacks:
    public: true

  DirkKlemmt\ContaoMmenuBundle\EventListener\SqlCompileCommandsListener:
    public: true
    arguments: ['@database_connection', '%kernel.project_dir%']
